#!/bin/bash
set -e

source settings.env

LATEST=${1}
SYSTEM=${2}

if [ ! -n "${LATEST}" ]
then
  LATEST="${U_SAKOMAN_LATEST}"
fi

if [ "desktop" != "${SYSTEM}" ]
then
  SYSTEM="console"
fi

MACHINE=${U_OE_MACHINE}
URL="http://www.sakoman.com/feeds/omap3/glibc/images/${MACHINE}/${LATEST}"
mkdir -p "${U_SAKOMAN_PATH}/${MACHINE}/${LATEST}"

cd "${U_SAKOMAN_PATH}/${MACHINE}/${LATEST}"
wget "${URL}/md5sum.txt"
wget "${URL}/${MACHINE}-oe-commit-id.txt"
wget "${URL}/x-load-${MACHINE}-${LATEST}.bin.ift"
wget "${URL}/MLO-${MACHINE}-${LATEST}"
wget "${URL}/u-boot-${MACHINE}-${LATEST}.bin"
wget "${URL}/uImage-${MACHINE}-${LATEST}.bin"
wget "${URL}/omap3-${SYSTEM}-image-${MACHINE}-${LATEST}.tar.bz2"
