#!/bin/bash

set -e

if [ ! "root" == `whoami` ]
then
  echo "Usage: sudo $0 $@"
  exit 1
fi

overo-sdhc-partition $@
read -p "*Remove* and *Reinsert* the SDHC card!     (then press a key *after* you do that)"
overo-sdhc-format $@
overo-sdhc-popullate $@
