#!/bin/bash
set -e

BOOT_DIR=/home/shared/overo-boot-image
ROOT_DIR=/home/shared/overo-root-image
SAUCE_DIR=/home/coolaj86/overo-system-overlay
OE_DIR=/mnt/local/overo-coolaj86
IMAGE_DIR=${OE_DIR}/tmp/deploy/glibc/images/overo
IMAGE_NAME=console-image
IMAGE_TAR=${IMAGE_DIR}/${IMAGE_NAME}-overo.tar.bz2
function pre_overlay {
  #sudo rm ${ROOT_DIR}/etc/rc{3,4,5}.d -rf
}


cd ${OE_DIR}/
#bitbake ${IMAGE_NAME}
sudo rm -rf ${ROOT_DIR}
sudo mkdir -p ${ROOT_DIR}/
sudo tar xf ${IMAGE_TAR} -C ${ROOT_DIR}/
pre_overlay()
sudo rsync -a --exclude='.git' ${SAUCE_DIR} ${ROOT_DIR}
sudo chmod go-rwx -R ${ROOT_DIR}/home/root/ # for .ssh
sudo chown root:root -R ${ROOT_DIR}/home/root/ ${ROOT_DIR}/etc/

#bitbake x-load u-boot-omap3 virtual/kernel
#sudo rm -rf ${BOOT_DIR}
#sudo mkdir -p ${BOOT_DIR}/
#sudo cp ${IMAGE_DIR}/MLO-overo ${BOOT_DIR}/MLO 
#sudo cp ${IMAGE_DIR}/u-boot-overo.bin ${BOOT_DIR}/u-boot.bin
#sudo cp ${IMAGE_DIR}/uImage-overo.bin ${BOOT_DIR}/uImage

echo "Probably Successful. No known errors."
