#!/bin/bash
set -e

source settings.env

MACHINE=${U_OE_MACHINE}

FOLDER=${1}
DEVICE=${2}
SYSTEM=${3}
TMPDIR="/tmp/${MACHINE}-`random-string`"


if [ ! -n "${DEVICE}" ] || [ ! -n "${FOLDER}" ] || [ ! "root" == "`whoami`" ]
then
  echo "Usage: sudo ${0} SAKOMAN_DATED_IMAGE_FOLDER /dev/SDX [ desktop | console (default) ]"
  echo "Example: sudo ${0} ./${MACHINE}/201011150741 /dev/sdi console"
  exit 1
fi

if [ "desktop" != "${SYSTEM}" ]
then
  SYSTEM="console"
fi

# TODO strip trailing slash

cd ${FOLDER}
overo-sdhc-partition ${DEVICE}
read -p "*Remove* and *Reinsert* the SDHC card!     (then press a key *after* you do that)"
overo-sdhc-format ${DEVICE}
mkdir -p ${TMPDIR}
mount ${DEVICE}1 ${TMPDIR}
echo "Copying boot files (should only take a few seconds)"
cp MLO-${MACHINE}-${FOLDER} ${TMPDIR}/MLO
cp u-boot-${MACHINE}-${FOLDER}.bin ${TMPDIR}/u-boot.bin
cp uImage-${MACHINE}-${FOLDER}.bin ${TMPDIR}/uImage
sync
umount ${TMPDIR}
mount ${DEVICE}2 ${TMPDIR}
echo "Copying ${SYSTEM} image files (may take several minutes)"
tar xf omap3-${SYSTEM}-image-${MACHINE}-${FOLDER}.tar.bz2 -C ${TMPDIR}
umount ${DEVICE}2
rmdir ${TMPDIR}
