#!/bin/bash

DATE=`date +%F`
OE_BITBAKE_VER="1.10.2"
OVEROTOP=~/overo-oe
OE_REPO=org.openembedded.dev

mkdir -p ${OVEROTOP}


cd ${OVEROTOP}
  if [ ! -e "${OE_REPO}/.git" ]
  then
    rm -rf "${OE_REPO}"
    git clone git://gitorious.org/gumstix-oe/mainline.git ${OE_REPO}
  fi
  cd ${OE_REPO}
    git fetch
    git checkout --track -b overo origin/overo
    git checkout ${U_OE_CHECKOUT}
  cd -
cd ~/


cd ${OVEROTOP}
  if [ ! -e "bitbake/.git" ]
  then
    rm -rf bitbake
    git clone git://git.openembedded.net/bitbake bitbake
  fi
  cd bitbake
    git checkout ${OE_BITBAKE_VER}
  cd -
cd ~/


cd ${OVEROTOP}
  if [ ! -e "build" ]
  then
    cp -r ${OE_REPO}/contrib/gumstix/build ./
  fi
cd ~/


cp ~/.bashrc ~/bashrc.${DATE}.bak
cat ${OVEROTOP}/build/profile >> ~/.bashrc
. ${OVEROTOP}/build/profile


cd ${OVEROTOP}
  # rm ./tmp -rf
  bitbake gcc-cross-sdk
  #bitbake omap3-console-image
  #bitbake u-boot-omap3
  #bitbake x-load
cd ~/
